package renderer

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/glincker/stacklit/internal/schema"
)

func makeRichTestIndex() *schema.Index {
	return &schema.Index{
		GeneratedAt: "2026-05-05T00:00:00Z",
		Project: schema.Project{
			Name: "myapp",
			Type: "monorepo",
		},
		Tech: schema.Tech{
			PrimaryLanguage: "go",
			Languages: map[string]schema.LangStats{
				"go":         {Files: 10, Lines: 5000},
				"typescript": {Files: 4, Lines: 1234},
			},
			Frameworks: []string{"Gin", "React"},
		},
		Structure: schema.Structure{
			Entrypoints: []string{"cmd/api/main.go", "cmd/worker/main.go"},
			TotalFiles:  14,
			TotalLines:  6234,
			KeyDirectories: map[string]string{
				"cmd/":      "binaries",
				"internal/": "private packages",
			},
		},
		Modules: map[string]schema.ModuleInfo{
			"src/api": {
				Purpose:   "API handlers (with | pipe in purpose)",
				Files:     5,
				Lines:     1200,
				Exports:   []string{"NewServer()", "RegisterRoutes()"},
				DependsOn: []string{"src/auth", "src/db"},
				TypeDefs: map[string]string{
					"Server": "router *gin.Engine, port int",
				},
			},
			"src/auth": {
				Purpose:   "Authentication",
				Files:     3,
				Lines:     500,
				Exports:   []string{"Authenticate(token string) (User, error)"},
				DependsOn: []string{"src/db"},
			},
			"src/db": {
				Purpose: "Database access layer",
				Files:   4,
				Lines:   800,
			},
		},
		Dependencies: schema.Dependencies{
			Edges: [][2]string{
				{"src/api", "src/auth"},
				{"src/api", "src/db"},
				{"src/auth", "src/db"},
			},
			MostDepended: []string{"src/db"},
			Isolated:     []string{"scripts"},
		},
		Git: schema.GitInfo{
			HotFiles: []schema.HotFile{
				{Path: "src/api/server.go", Commits90d: 12},
				{Path: "src/auth/jwt.go", Commits90d: 7},
			},
		},
		Hints: schema.Hints{
			AddFeature: "Create handler in src/api/, add route in src/api/routes.go",
			TestCmd:    "go test ./...",
			EnvVars:    []string{"DATABASE_URL", "JWT_SECRET"},
		},
	}
}

func TestRenderMarkdownContainsExpectedSections(t *testing.T) {
	idx := makeRichTestIndex()
	out := RenderMarkdown(idx)

	wantSubstrings := []string{
		"# myapp",
		"go · monorepo · 14 files · 6,234 lines",
		"## Overview",
		"| Language | Files | Lines |",
		"| go | 10 | 5,000 |",
		"Frameworks: Gin, React",
		"## Entrypoints",
		"- `cmd/api/main.go`",
		"- `cmd/worker/main.go`",
		"## Key directories",
		"- `cmd/` — binaries",
		"## Modules",
		"| `src/api` |",
		"## Module details",
		"<details><summary><code>src/api</code></summary>",
		"`NewServer()`",
		"## Dependencies",
		"Most depended on: `src/db`",
		"Isolated: `scripts`",
		"- `src/api` → `src/auth`",
		"## Hot files (last 90 days)",
		"`src/api/server.go`",
		"## Hints",
		"- Run tests: `go test ./...`",
		"- Env vars: `DATABASE_URL`, `JWT_SECRET`",
		"Generated by [stacklit]",
	}

	for _, w := range wantSubstrings {
		if !strings.Contains(out, w) {
			t.Errorf("expected output to contain %q\n--- output ---\n%s", w, out)
		}
	}
}

func TestRenderMarkdownEscapesPipeInTableCell(t *testing.T) {
	idx := makeRichTestIndex()
	out := RenderMarkdown(idx)

	// The purpose string for src/api contains a pipe; it must be escaped so
	// it doesn't break the table row.
	if !strings.Contains(out, `with \| pipe`) {
		t.Errorf("expected pipe in module purpose to be escaped to '\\|', got:\n%s", out)
	}
}

func TestRenderMarkdownIsDeterministic(t *testing.T) {
	idx := makeRichTestIndex()
	first := RenderMarkdown(idx)
	for i := 0; i < 5; i++ {
		again := RenderMarkdown(idx)
		if again != first {
			t.Fatalf("RenderMarkdown is not deterministic on run %d", i+2)
		}
	}
}

func TestRenderMarkdownEmptyIndex(t *testing.T) {
	idx := &schema.Index{
		Project:      schema.Project{Name: ""},
		Tech:         schema.Tech{Languages: map[string]schema.LangStats{}},
		Modules:      map[string]schema.ModuleInfo{},
		Dependencies: schema.Dependencies{},
	}
	out := RenderMarkdown(idx)

	if !strings.Contains(out, "# Project") {
		t.Errorf("expected fallback title '# Project' for empty index, got:\n%s", out)
	}
	// Sections that depend on data should be absent.
	for _, section := range []string{"## Modules", "## Dependencies", "## Hot files", "## Hints"} {
		if strings.Contains(out, section) {
			t.Errorf("did not expect %q section in empty index, got:\n%s", section, out)
		}
	}
}

func TestWriteMarkdownIsIdempotent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "stacklit.md")
	idx := makeRichTestIndex()

	if err := WriteMarkdown(idx, path); err != nil {
		t.Fatalf("first WriteMarkdown failed: %v", err)
	}
	first, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat after first write: %v", err)
	}

	// Sleep-free: check that a second identical write doesn't change the file.
	// We compare contents directly since modtime can be unreliable on fast filesystems.
	firstBytes, _ := os.ReadFile(path)

	if err := WriteMarkdown(idx, path); err != nil {
		t.Fatalf("second WriteMarkdown failed: %v", err)
	}
	secondBytes, _ := os.ReadFile(path)

	if string(firstBytes) != string(secondBytes) {
		t.Errorf("WriteMarkdown produced different content on second run")
	}

	// Sanity: the file is non-trivial in size.
	if first.Size() < 100 {
		t.Errorf("expected markdown output to be > 100 bytes, got %d", first.Size())
	}
}

func TestFormatThousands(t *testing.T) {
	cases := []struct {
		in   int
		want string
	}{
		{0, "0"},
		{42, "42"},
		{999, "999"},
		{1000, "1,000"},
		{6234, "6,234"},
		{1234567, "1,234,567"},
	}
	for _, tc := range cases {
		if got := formatThousands(tc.in); got != tc.want {
			t.Errorf("formatThousands(%d) = %q, want %q", tc.in, got, tc.want)
		}
	}
}
