package renderer

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strings"
	"time"
	"unicode"

	"github.com/glincker/stacklit/internal/schema"
)

// langColors maps language names to neutral monochrome colors.
var langColors = map[string][2]string{
	"go":         {"#e6edf3", "#0d1117"},
	"typescript": {"#c9d1d9", "#0d1117"},
	"javascript": {"#c9d1d9", "#0d1117"},
	"python":     {"#b1bac4", "#0d1117"},
	"rust":       {"#a5b3bf", "#0d1117"},
	"java":       {"#8b949e", "#0d1117"},
	"csharp":     {"#8b949e", "#0d1117"},
	"ruby":       {"#8b949e", "#0d1117"},
	"php":        {"#8b949e", "#0d1117"},
	"swift":      {"#8b949e", "#0d1117"},
	"kotlin":     {"#8b949e", "#0d1117"},
	"c":          {"#8b949e", "#0d1117"},
	"cpp":        {"#8b949e", "#0d1117"},
	"scala":      {"#8b949e", "#0d1117"},
	"elixir":     {"#8b949e", "#0d1117"},
}

// sanitizeMermaidID converts a module path to a valid Mermaid node ID.
// e.g. "src/auth" → "src_auth", "@test/api" → "test_api"
func sanitizeMermaidID(name string) string {
	var sb strings.Builder
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			sb.WriteRune(r)
		} else {
			sb.WriteRune('_')
		}
	}
	result := strings.Trim(sb.String(), "_")
	// Collapse consecutive underscores
	for strings.Contains(result, "__") {
		result = strings.ReplaceAll(result, "__", "_")
	}
	return result
}

// truncate shortens s to at most n runes, appending "…" if truncated.
func truncate(s string, n int) string {
	runes := []rune(s)
	if len(runes) <= n {
		return s
	}
	return string(runes[:n]) + "…"
}

// WriteMermaid generates a Mermaid graph LR diagram from idx and writes it to path.
func WriteMermaid(idx *schema.Index, path string) error {
	var sb strings.Builder

	// Header with generation date and project info.
	name := idx.Project.Name
	if name == "" {
		name = "project"
	}
	sb.WriteString(fmt.Sprintf("# %s dependency graph\n\n", name))
	sb.WriteString(fmt.Sprintf("> Generated by [stacklit](https://github.com/glincker/stacklit) on %s. Run `stacklit generate` to update.\n\n", time.Now().UTC().Format("2006-01-02")))
	sb.WriteString("```mermaid\ngraph LR\n")

	// Collect which languages are actually used by modules.
	usedLangs := map[string]bool{}
	for _, mod := range idx.Modules {
		_ = mod // language info not on ModuleInfo; use Tech.Languages from idx
	}
	for lang := range idx.Tech.Languages {
		lang = strings.ToLower(lang)
		if _, ok := langColors[lang]; ok {
			usedLangs[lang] = true
		}
	}

	// Write classDef entries for used languages in deterministic order.
	langs := make([]string, 0, len(usedLangs))
	for lang := range usedLangs {
		langs = append(langs, lang)
	}
	sort.Strings(langs)
	for _, lang := range langs {
		colors := langColors[lang]
		sb.WriteString(fmt.Sprintf("  classDef %s fill:%s,color:%s,stroke:%s\n",
			lang, colors[0], colors[1], colors[0]))
	}

	// Determine primary language for node class assignment.
	primaryLang := strings.ToLower(idx.Tech.PrimaryLanguage)

	// Write node definitions in deterministic order.
	moduleNames := make([]string, 0, len(idx.Modules))
	for name := range idx.Modules {
		moduleNames = append(moduleNames, name)
	}
	sort.Strings(moduleNames)
	for _, name := range moduleNames {
		mod := idx.Modules[name]
		id := sanitizeMermaidID(name)
		label := truncate(mod.Purpose, 40)
		nodeClass := primaryLang
		if _, ok := langColors[nodeClass]; !ok {
			nodeClass = ""
		}
		if nodeClass != "" {
			sb.WriteString(fmt.Sprintf("  %s[\"%s<br/>%s\"]:::%s\n", id, name, label, nodeClass))
		} else {
			sb.WriteString(fmt.Sprintf("  %s[\"%s<br/>%s\"]\n", id, name, label))
		}
	}

	// Write edges.
	for _, edge := range idx.Dependencies.Edges {
		from := sanitizeMermaidID(edge[0])
		to := sanitizeMermaidID(edge[1])
		sb.WriteString(fmt.Sprintf("  %s --> %s\n", from, to))
	}

	sb.WriteString("```\n")
	data := []byte(sb.String())
	if existing, err := os.ReadFile(path); err == nil && bytes.Equal(existing, data) {
		return nil
	}
	return os.WriteFile(path, data, 0644)
}
